import "./assets/styles/style.scss"

export { default as HeaderAnimation } from "./animations/header"
export { default as AboutAnimation } from "./animations/about"
export { default as AiAnimation } from "./animations/ai"
export { default as BigDataAnimation} from "./animations/bigdata-animation"
export { default as CloudComputingAnimation } from "./animations/cloud-computing"
export { default as CyberSecurityAnimation } from "./animations/cyber-security"
export { default as EnterpriseCollabAnimation } from "./animations/enterprise-collab"
export { default as EnterpriseProductAnimation } from "./animations/enterprise-product"
export { default as PolicyManagementAnimation } from "./animations/policy-management"
export { default as TechnologyAnimation } from "./animations/technology"